security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CMSBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: ROLE_ADMIN }
                    superadmin: { password: superpass, roles: ROLE_SUPER_ADMIN }
        user_db:
            entity: { class: CMSBundle:User, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/
            logout:
                path: /logout
                target: /admin/login
            security: true
            anonymous: true
    access_control:
        - { path: /admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/*, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
