<?php

namespace CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InfographicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfographicRepository extends EntityRepository
{
}
