admin_article_index:
    path:     /
    defaults: { _controller: "CMSBundle:Article:index" }
    methods:  GET

admin_article_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBundle:Article:show" }
    methods:  GET

admin_article_new:
    path:     /new
    defaults: { _controller: "CMSBundle:Article:new" }
    methods:  [GET, POST]

admin_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBundle:Article:edit" }
    methods:  [GET, POST]

admin_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBundle:Article:delete" }
    methods:  DELETE

admin_article_city:
    path:     /{id}/
    defaults: { _controller: "CMSBundle:Article:content" }
    methods:  GET

admin_article_city_new:
    path:     /new/{id}
    defaults: { _controller: "CMSBundle:Article:newcity" }
    methods:  [GET, POST]