admin_infographic_index:
    path:     /
    defaults: { _controller: "CMSBundle:Infographic:index" }
    methods:  GET

admin_infographic_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBundle:Infographic:show" }
    methods:  GET

admin_infographic_new:
    path:     /new
    defaults: { _controller: "CMSBundle:Infographic:new" }
    methods:  [GET, POST]

admin_infographic_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBundle:Infographic:edit" }
    methods:  [GET, POST]

admin_infographic_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBundle:Infographic:delete" }
    methods:  DELETE

admin_infographic_city:
    path:     /{id}/
    defaults: { _controller: "CMSBundle:Infographic:content" }
    methods:  GET

admin_infographic_city_new:
    path:     /new/{id}
    defaults: { _controller: "CMSBundle:Infographic:newcity" }
    methods:  [GET, POST]
