admin_lanuage_index:
    path:     /
    defaults: { _controller: "CMSBundle:Language:index" }
    methods:  GET

admin_lanuage_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBundle:Language:show" }
    methods:  GET

admin_lanuage_new:
    path:     /new
    defaults: { _controller: "CMSBundle:Language:new" }
    methods:  [GET, POST]

admin_lanuage_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBundle:Language:edit" }
    methods:  [GET, POST]

admin_lanuage_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBundle:Language:delete" }
    methods:  DELETE
